# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-13 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_booked', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=3), max_length=320, size=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_name', models.CharField(max_length=200)),
                ('cinema_addr', models.CharField(max_length=200)),
                ('cinema_contact', models.CharField(max_length=20)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=8)),
                ('leadImageUrl', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=4, max_digits=8)),
                ('leadImageUrl', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('poster', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('release_date', models.DateTimeField(verbose_name='date released')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showing_time', models.DateTimeField(verbose_name='show time')),
                ('showing_date', models.DateTimeField(verbose_name='show date')),
                ('seat', django_mysql.models.ListCharField(models.CharField(max_length=3), max_length=320, size=80)),
                ('seat_booked', django_mysql.models.ListCharField(models.CharField(blank=True, max_length=3), max_length=320, size=80)),
                ('cinema', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Booking.Cinema')),
                ('movie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Booking.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='cinema_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.City'),
        ),
    ]
