# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='show',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Booking.Showing'),
            preserve_default=False,
        ),
    ]
